spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ////////////
    password: mgvh anwa qczd avbj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
